{
    'name': 'Website Product Pdf Catalog',
    'version': '18.0.1.0.0',
    'summary': '',
    'sequence': 1,
    'description': """""",
    'category': '',
    'author': 'Weblytic Labs',
    'company': 'Weblytic Labs',
    'website': 'https://store.weblyticlabs.com',
    'price': '',
    'currency': '',
    'depends': ['base', 'base_setup', 'website', 'website_sale', 'sale_management', 'contacts'],
    'data': [
        'views/res_config_settings_view.xml',
        'views/product_template.xml',
        'reports/action_all_product_details.xml',
        'reports/all_product_details_pdf.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
